### ISSUE TITLE
Autocomplete fails to insert suggestion; virtual_keyword not defined per default

### ISSUE THREAD

**Issue by ghost** [etienne-monier/LedgerTools#4]
Sublime Text 4, latest version of LedgerTools, macOS 11.4

Hitting ctrl+shift+a shows a list of accounts, but selecting one and hitting enter does nothing.
Console shows the following error:

    Traceback (most recent call last):
      File "/Users/ueberbelichtetesfoto/Library/Application Support/Sublime Text/Installed Packages/LedgerTools.sublime-package/SearchAccountPayee.py", line 73, in <lambda>
      File "/Users/ueberbelichtetesfoto/Library/Application Support/Sublime Text/Installed Packages/LedgerTools.sublime-package/SearchAccountPayee.py", line 77, in pick
      File "/Users/ueberbelichtetesfoto/Library/Application Support/Sublime Text/Installed Packages/LedgerTools.sublime-package/SearchAccountPayee.py", line 63, in run
      File "./python3.3/re.py", line 161, in search
      File "./python3.3/re.py", line 282, in _compile
    TypeError: first argument must be string or compiled pattern

Selecting a payee with ctrl+shift+z results in the same.

The problematic line is
https://github.com/etienne-monier/LedgerTools/blob/4f214b283b521180cea7a5d637f42be2064ff9cc/SearchAccountPayee.py#L60

`virtual_keyword` is not defined per default in the settings file.

Adding `"virtual_keyword": "",` to LedgerTools.sublime-settings fixes the issue.

It seems that 4f214b283b521180cea7a5d637f42be2064ff9cc introduced this bug.

**Comment by etienne-monier** [comment]
Thanks @ueberbelichtetesfoto :)

I saw this error on my local repo, and time has gone without pushing it. My fault !

That's updated on github, soon on PackageControl. Update for fixing.

I see you're new to github. Glad to see a new bug reporter :) Thanks for reporting this issue :)
